# Generated by Django 3.2 on 2023-03-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='краткое название продукта', max_length=200, verbose_name='название продукта')),
                ('image', models.ImageField(upload_to='products', verbose_name='фото продукта')),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(help_text='отображается в карточке', max_length=64, verbose_name='краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productcategory', verbose_name='категория')),
            ],
        ),
    ]
